development:
  MEME_FONT_LOCATION: "./app/assets/fonts/Impact.ttf"
  WATERMARK_FONT_LOCATION: "./app/assets/fonts/Arial.ttf"

production:
  MEME_FONT_LOCATION: "./app/assets/fonts/Impact.ttf"
  WATERMARK_FONT_LOCATION: "./app/assets/fonts/Arial.ttf"
